2025-02-18 11:07:29,403 - INFO - Loading and preprocessing data...
2025-02-18 11:07:29,404 - INFO - Loading ratings data...
2025-02-18 11:07:58,932 - INFO - 
Validating ratings DataFrame:
2025-02-18 11:08:04,252 - INFO - Shape: 20000263 rows, 4 columns
2025-02-18 11:08:33,655 - ERROR - An error occurred: [DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve "isnan(timestamp)" due to data type mismatch: Parameter 1 requires the ("DOUBLE" or "FLOAT") type, however "timestamp" has the type "TIMESTAMP".;
'Filter (isnull(timestamp#20) OR isnan(timestamp#20))
+- Relation [userId#17,movieId#18,rating#19,timestamp#20] csv
Traceback (most recent call last):
  File "C:\Users\efeba\BIL401Proje\src\main.py", line 109, in main
    ratings_df, movies_df, tags_df, genome_scores_df, genome_tags_df = load_and_preprocess_data(data_loader)
  File "C:\Users\efeba\BIL401Proje\src\main.py", line 39, in load_and_preprocess_data
    ratings_df = data_loader.load_ratings()
  File "C:\Users\efeba\BIL401Proje\src\data_loader.py", line 74, in load_ratings
    ratings_df = self.validate_dataframe(ratings_df, "ratings")
  File "C:\Users\efeba\BIL401Proje\src\data_loader.py", line 37, in validate_dataframe
    null_count = df.filter(col(column).isNull() | isnan(column)).count()
  File "C:\spark\python\pyspark\sql\dataframe.py", line 3331, in filter
    jdf = self._jdf.filter(condition._jc)
  File "C:\spark\python\lib\py4j-0.10.9.7-src.zip\py4j\java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "C:\spark\python\pyspark\errors\exceptions\captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve "isnan(timestamp)" due to data type mismatch: Parameter 1 requires the ("DOUBLE" or "FLOAT") type, however "timestamp" has the type "TIMESTAMP".;
'Filter (isnull(timestamp#20) OR isnan(timestamp#20))
+- Relation [userId#17,movieId#18,rating#19,timestamp#20] csv

2025-02-18 11:08:34,287 - INFO - Closing down clientserver connection
2025-02-18 11:10:29,885 - INFO - Loading and preprocessing data...
2025-02-18 11:10:29,885 - INFO - Loading ratings data...
2025-02-18 11:10:56,765 - INFO - 
Validating ratings DataFrame:
2025-02-18 11:11:00,432 - INFO - Shape: 20000263 rows, 4 columns
2025-02-18 11:13:31,744 - INFO - Loading movies data...
2025-02-18 11:13:32,371 - INFO - 
Validating movies DataFrame:
2025-02-18 11:13:32,551 - INFO - Shape: 27278 rows, 3 columns
2025-02-18 11:13:35,503 - ERROR - An error occurred: name 'regexp_extract' is not defined
Traceback (most recent call last):
  File "C:\Users\efeba\BIL401Proje\src\main.py", line 114, in main
    ratings_df, movies_df, tags_df, genome_scores_df, genome_tags_df = load_and_preprocess_data(data_loader)
  File "C:\Users\efeba\BIL401Proje\src\main.py", line 40, in load_and_preprocess_data
    movies_df = data_loader.load_movies()
  File "C:\Users\efeba\BIL401Proje\src\data_loader.py", line 122, in load_movies
    regexp_extract(col("title"), ".*\\((\\d{4})\\)$", 1).cast("integer")
NameError: name 'regexp_extract' is not defined
